## Numpy 

# Creating Numpy Array from python lists

In [1]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.array([4.3,1,2,3,4,5]) # in numpy , it will be converted to the data types which is greater float > integer

array([4.3, 1. , 2. , 3. , 4. , 5. ])

In [8]:
np.array([1,2,3,4,5,6.7],dtype='float')# you can specify the data types of array

array([1. , 2. , 3. , 4. , 5. , 6.7])

In [11]:
a1 =  np.array([1,2,3])
type(a1)

numpy.ndarray

In [15]:
a2 =  np.array([
    [1,2,3],
    [4,5,6]
])
type(a2)

numpy.ndarray

In [17]:
a2.shape #like as data frame, it also has the shape => (rows,columns)

(2, 3)

In [20]:
a2.ndim # how many dimenstion in this a2 array

2

In [22]:
a2.size

6

# Creating Numpy array from Scratch
*zeros,ones,full,arange,linspace*

In [28]:
np.zeros([2,5],dtype='int') 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.ones([2,5],dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.arange(0,20,2) # (start,end,steps)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.full([3,5],np.inf)

array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [43]:
#Creating an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [134]:
#Seed for reproducibility
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [130]:
np.random.random([4,4])

array([[0.23780724, 0.1718531 , 0.44929165, 0.30446841],
       [0.83918912, 0.23774183, 0.50238946, 0.9425836 ],
       [0.6339977 , 0.86728941, 0.94020969, 0.75076486],
       [0.69957506, 0.96796557, 0.99440079, 0.45182168]])